version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'pa55w0rd!'
    ports:
      - '1433:1433'
  dockercomposedemo:
    build: .
    ports:
      - '8080:80'
      - '8081:443'
    environment:
      ASPNETCORE_URLS: 'https://+;http://+'
      ASPNETCORE_HTTPS_PORT: '8081'
      ASPNETCORE_ENVIRONMENT: 'Development'
      DBServer: 'ms-sql-server'
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
